name: lint
on: push
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      YARN_CACHE: ${{ steps.setup-yarn.outputs.YARN_CACHE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup yarn
        id: setup-yarn
        run: |
          corepack enable
          yarn --version
          echo "YARN_CACHE=`yarn config get cacheFolder`" >> "$GITHUB_OUTPUT"

      - name: Configure node_modules cache
        id: node-modules
        uses: actions/cache@v4
        env:
          cache-name: node-modules
        with:
          path: |
            ${{ steps.setup-yarn.outputs.YARN_CACHE }}
          key: ${{ runner.os }}-setup-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}-v1

      - name: Install node modules
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: yarn install --immutable

  lint:
    name: Lint www.shorelinetennisclub.com
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup yarn
        run: |
          corepack enable
          yarn --version

      - name: Restore node_modules cache
        uses: actions/cache@v4
        env:
          cache-name: node-modules
        with:
          path: |
            ${{ needs.setup.outputs.YARN_CACHE }}
          key: ${{ runner.os }}-setup-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}-v2

      - name: Generate lint report for annotation
        run: pnpm lint:report
        # Continue to the next step even if this fails
        continue-on-error: true

      # Needs write permission: https://github.com/ataylorme/eslint-annotate-action/issues/28
      - name: Annotate based on lint report
        uses: ataylorme/eslint-annotate-action@v2
        with:
          markdown-report-on-step-summary: true
          fail-on-warning: true
          only-pr-files: false
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "tmp/eslint_report.json"

      - name: Upload lint report
        uses: actions/upload-artifact@v4
        with:
          name: eslint_report.json
          path: tmp/eslint_report.json

      - name: Lint for keeps
        run: pnpm lint

  tsc:
    name: Type check www.shorelinetennisclub.com
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup yarn
        run: |
          corepack enable
          yarn --version

      - name: Restore node_modules cache
        uses: actions/cache@v4
        env:
          cache-name: node-modules
        with:
          path: |
            ${{ needs.setup.outputs.YARN_CACHE }}
          key: ${{ runner.os }}-setup-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}-v2

      - name: TSC
        run: ls -al src/assets

      - name: TSC
        run: yarn ts -p ./tsconfig.json

permissions:
  checks: write
  pull-requests: read
